# Generated by Django 4.1.5 on 2023-01-19 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default=None, max_length=100)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("S", "Single Occupancy"),
                            ("D", "Double Occupancy"),
                            ("P", "Reserved for Research Scholars"),
                            ("B", "Both Single and Double Occupancy"),
                        ],
                        default="D",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=5)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        default=None,
                        max_length=1,
                        null=True,
                    ),
                ),
                ("caretaker", models.CharField(blank=True, max_length=100)),
                (
                    "course",
                    models.ManyToManyField(blank=True, default=None, to="app.course"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no", models.CharField(max_length=5)),
                ("name", models.CharField(max_length=10)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("S", "Single Occupancy"),
                            ("D", "Double Occupancy"),
                            ("P", "Reserved for Research Scholars"),
                            ("B", "Both Single and Double Occupancy"),
                        ],
                        default=None,
                        max_length=1,
                    ),
                ),
                ("vacant", models.BooleanField(default=False)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.hostel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200, null=True)),
                ("last_name", models.CharField(max_length=200, null=True)),
                (
                    "enrollment_no",
                    models.CharField(max_length=10, null=True, unique=True),
                ),
                (
                    "dob",
                    models.DateField(
                        help_text="format : YYYY-MM-DD", max_length=10, null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        default=None,
                        max_length=1,
                        null=True,
                    ),
                ),
                ("room_allotted", models.BooleanField(default=False)),
                ("no_dues", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.course",
                    ),
                ),
                (
                    "room",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.room",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
