# Generated by Django 4.1.5 on 2023-01-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("SINGLE", "Single Occupancy"),
                    ("DOUBLE", "Double Occupancy"),
                    ("RESERVED", "Reserved for Research Scholars"),
                    ("SUITE", "Both Single and Double Occupancy"),
                ],
                default="D",
                max_length=10,
            ),
        ),
    ]
